### PR TITLE
Travis: cache .stack dir

### PR DESCRIPTION
**Pull request by develop7**
cache `$HOME/.stack` dir (hopefully) improving consecutive build times

### CODE REVIEW

**Comment by develop7** [comment]
@chrisdone pls trigger rebuild in Travis so we could see if cache does actually bring any improvement

**Comment by purcell** [comment]
I restarted the [previous build](https://travis-ci.org/commercialhaskell/intero/builds/449851012?utm_source=github_status&utm_medium=notification), which had taken 36m.

**Comment by develop7** [comment]
OK, so results:

| Build | Time |
| --- | --- |
| [cached build](https://travis-ci.org/commercialhaskell/intero/builds/449851012) | 12:24 |
| [master branch](https://travis-ci.org/commercialhaskell/intero/builds/449842512) | 28:04 |

**Comment by develop7** [comment]
Please note the caches are per-branch (along other "per-"s) so no immediate speedup after merging.

**Comment by purcell** [comment]
I'll merge this, but note that the Travis caches can get pretty big, and at that point they often become so slow to store and fetch that they make the build slower, not faster. So let's keep an eye on how this works out in practice.

**Pull request merged**
