### PR TITLE
Allow building with GHC-8.4.4

### LINKED ISSUE #586: Intero in stackage lts-12.15 and lts-12.16 can't build
### Steps to replicate
* Create a new Stack project with `lts-12.16`
* `stack install intero`

### Expected
Build to succeed

### Actual

Fails with:
```
In the dependencies for intero-0.1.32:
    ghc-8.4.4 from stack configuration does not match >=7.8 && <=8.4.3  (latest matching version is 8.4.3)
needed since intero is a build target.
```

### Notes
[lts-12.15](https://www.stackage.org/lts-12.15) and [lts-12.16](https://www.stackage.org/lts-12.16) both include `ghc-8.4.4`, and  `intero-0.1.32`,

Looks similar to #582, though I think that was referring to different versions.

### PR DESCRIPTION
**Pull request by acowley**
Fixes #586

### CODE REVIEW

**Comment by telser** [comment]
This would be a big help with the project/team I'm currently working on.

**Comment by chrisdone** [comment]
Testing myself and then I'll push a release.

**Comment by chrisdone** [comment]
Updated.

**Comment by cdfa** [comment]
This still isn't working for me, but I don't understand why. I get the following output:
```
Populated index cache.
Didn't see ghci-8.4.4 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
No updates to your package index were found
Update complete
The following package identifiers were not found in your indices: ghci-8.4.4
Possible candidates: ghci-8.4.3, ghci-8.4.1, ghci-8.4.2.
```
Hackage says the maximal version is 8.6.1, but when i try to run `stack install intero` it complains that it can't find ghci-8.4.4, which is the ghc version selected by `lts-12.18` in my stack.yaml and is installed in `~/.stack/programs/x86_64-linux/`. ghc-8.4.4 is not on hackage though for some reason.
Can anyone help?

**Pull request merged**
