### PR TITLE
Make intero compile with ghc 8.6.1

### PR DESCRIPTION
**Pull request by janpath**

### CODE REVIEW

**Comment by purcell** [comment]
Any issues with this, @chrisdone? LGTM.

**Comment by acowley** [comment]
It would be good to merge this rather than the [8.4.4 stopgap](https://github.com/commercialhaskell/intero/pull/587), but when I tried [adding CI for 8.4.4 and 8.6.1](https://github.com/acowley/intero/commit/d2d68003476dfeb929237c168c2e644b8d9981a5) I ran into [deprecation errors](https://travis-ci.org/acowley/intero/jobs/449443624) from the use of `Network`.

Perhaps adopting [network-simple](http://hackage.haskell.org/package/network-simple) would be the simplest transition.

**Comment by chrisdone** [comment]
Looks good! Merging.

**Comment by chrisdone** [comment]
Thanks a lot @janpath! I owe you a :beer: or other beverage of choice.

**Comment by chrisdone** [comment]
Pushed to hackage as 0.1.34. Waiting on stackage and then I'll update the elisp. Takes ~30 mins.

**Comment by janpath** [comment]
@chrisdone Your welcome. I'll remind you of the beer if I ever meet you. ;)

**Comment by jakubdaniel** [comment]
> Waiting on stackage and then I'll update the elisp. Takes ~30 mins.

Pardon my ignorance, I can't seem to pinpoint at what stage this got stuck. Is anything blocking update of the elisp? I am not familiar with the process behind curating packages for stackage and can't find any status of intero with respect to nightlies or future lts.

**Comment by chrisdone** [comment]
Pushed update to elisp to 0.1.34 now that it's up on stackage.

**Comment by chrisdone** [comment]
@jakubdaniel The stackage server's package index updates every 30-60 minutes. If I update the .el to demand 0.1.34, then stack will fail to download that version if it's not up on stackage yet, leading to a broken dev environment. So I just wait until it's uploaded.

In this case I somehow had the tab open and forgot to come back to it after an hour and just noticed it 7 days later.

**Comment by jakubdaniel** [comment]
@chrisdone fair enough :). I honestly did not know, since neither [https://www.stackage.org/package/intero](https://www.stackage.org/package/intero) nor [https://www.stackage.org/package/intero/snapshots](https://www.stackage.org/package/intero/snapshots) show(ed) 0.1.34. Thanks a lot

**Comment by glaebhoerl** [comment]
I still don't see intero among any of the recent stackage snapshots, maybe because they're on 8.6.2 now and according to [hackage](http://hackage.haskell.org/package/intero) intero's upper bound is still 8.6.1?

**Pull request merged**
