### PR TITLE
Push find-tag-marker-ring so alt-* goes back from goto-definition

### PR DESCRIPTION
**Pull request by Peaker**

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Oh thanks, this should fix half of #81 (ahem, haven't tested). What about `M-,`? I guess it doesn't make sense with `intero` — should it be overriden to give an error?

**Comment by k-bx** [comment]
@Blaisorblade oh, please don't override `M-,` for an error, I'm still using it with regular TAGS which still work superior to intero sometimes (and can understand different languages or other things interesting for you).

**Comment by chrisdone** [comment]
I'll merge this in a minute. @purcell commented when he merged it into MELPA that I should add this, but he added some extra backwards compatibility in the code. I'll incorporate both things!

**Comment by chrisdone** [comment]
Reference here FYI: https://github.com/melpa/melpa/pull/3959#issuecomment-223711290

**Comment by chrisdone** [comment]
Merged and applied Purcell's suggestion too.

**Comment by purcell** [comment]
Yay, thanks for that!

**Pull request closed without merging**
