### PR TITLE
reapply 7309426 (configurable completion) which was removed in 9bef3b3

### PR DESCRIPTION
**Pull request by obadz**
removed in #46 by accident?

### CODE REVIEW

**Comment by chrisdone** [comment]
Oh, woops. I think I reset too far while doing that.

**Comment by obadz** [comment]
Thanks, do you think we could get a version bump on hackage?

**Comment by chrisdone** [comment]
Pushed 0.1.14.

**Comment by obadz** [comment]
Thanks a lot!

**Pull request merged**
