### PR TITLE
Consistently use .stack-work/intero for temp files

### PR DESCRIPTION
**Pull request by purcell**
This allows all temp files to be seen by the stack commands, even when stack's docker support is enabled. See #279, #293.

### CODE REVIEW

**Comment by purcell** [comment]
@chrisdone I wondered whether `intero-destroy` would perhaps be the right place to delete the `.stack-work/intero` directory? How would we know when all intero processes for a given stack project are torn down?

**Comment by shanemikel** [comment]
Do we need to know when Intero process is dead, or is it enough to have the build attempt completed?  I suppose the reload command would require a persisting tmp source file, but would the behavior of this command meet our expectations anyhow?  If so, it needs to be updated upon a buffer change in Emacs (right?).

Further, I'm tempted to suggest lack of cleanup of this particular file will be far dwarfed by the garbage Stack leaves around regularly.

If cleanup is, however, simultaneously desirable and infeasible, we can request upstream support (Stack) of a mounted directory in /tmp...

**Comment by purcell** [comment]
Yeah, I'm not personally bothered by a few temp files being left around in the stack work dir.

**Comment by shanemikel** [comment]
I was merely speculating, as I have zero familiarity with the Intero code.  @chrisdone, what do you think about this?

**Comment by chrisdone** [comment]
I'm not too bothered either. We could definitely do _something_, like waiting for the process to start and then deleting the files, but we have more prominent issues to tackle.

**Comment by chrisdone** [comment]
Thanks @purcell!

**Pull request merged**
