### PR TITLE
Bump auto-installed intero version

### PR DESCRIPTION
**Pull request by Tritlo**
Bump the auto-installed intero version in the elisp file to be the latest version, 0.1.16.

### CODE REVIEW

**Comment by chrisdone** [comment]
What do you need this for?

**Comment by chrisdone** [comment]
Back at my desk. The Emacs mode doesn't use any features in `0.1.16` - why do you need this update? Doing so will force anyone who updates their elisp to reinstall intero.

**Comment by Tritlo** [comment]
Ah, I see. My mistake. I just thought it was weird that the version fetched by Emacs was not in sync with the latest version.

**Comment by chrisdone** [comment]
No worries. I might pop a comment in there explaining this as you're not the first to notice it, good eye.

**Pull request closed without merging**
