### PR TITLE
Cache calls to 'stack path'

### PR DESCRIPTION
**Pull request by sergv**
This is useful for Windows folks since 'stack path' can take noticeable amount of time even for a single buffer thanks to antivirus ~malware~ software. But the decision to cache may be controversial as it may store old state of the filesystem. Even if there would be a handle to reset cache, users will have to be educated about it and will have to remember to use it if something does not work as intended.

I certainy feel that caching would be beneficial for Windows users (of which I am a member of), but am aware of the drawbacks. Do you think this change could lead to unintended issues too big to justify the benefits?

### CODE REVIEW

**Comment by mgsloan** [comment]
How about invalidating the cache of `stack path` whenever the stack configuration changes?

**Comment by sergv** [comment]
That may be the solution. But how to detect when stack configuration changed? Should Emacs use a hash of `stack.yaml`?

**Comment by mgsloan** [comment]
Modification timestamps should be sufficient.

**Comment by purcell** [comment]
@sergv Is it really necessary to check the file size?

**Comment by sergv** [comment]
@purcell Well, I'd rather check it just to be sure. Do you think it's redundant in all conceivable circumstances?

**Comment by purcell** [comment]
> Well, I'd rather check it just to be sure. Do you think it's redundant in all conceivable circumstances?

I think anything short of hashing the file contents is going to have edge cases, so mod time is simple and sufficient. (P.S. There's the `buffer-hash` function, but it's not available in all our supported Emacs versions, and not worth reimplementing locally.)

**Comment by sergv** [comment]
Any update on this, please?

**Comment by sergv** [comment]
I just looked more closely and my submissions are total bollocks! Just the fact that `locate-dominating-file` returns a directory, not the `stack.yaml` file, is enough to make all this caching facility broken beyound repair. But then, if that gets fixed, it looks like calling `stack path` will be rendundant since it's not going to do anything more sophisticated than look up a directory with a `stack.yaml` file, which will be already performed by the elisp. I'll close this for now, lest it gets merged and thus adds my embarassing commits to the project's history.

**Pull request closed without merging**
