### PR TITLE
Add command to start the repl and have stack load all modules in the target

### PR DESCRIPTION
**Pull request by wuzzeb**
The new command `intero-repl-load-all-modules` starts a new repl without the --no-load GHCI flag, so that `stack ghci` loads all the modules for the given target.  It only works if you use the command the very first time you start the repl, but you can quit GHCI and kill the buffer if you want to restart.

### CODE REVIEW

**Comment by chrisdone** [comment]
I'm reluctant to add a new command, as this feature could be added to the existing command. But I like the idea to optionally load everything.

Proposal:

With the `C-u` prefix argument before running `intero-repl` or `intero-repl-load`, it brings up a little options menu, similar to magit. This would look a bit [like this](https://github.com/commercialhaskell/intero/issues/56#issue-158493916), so we could re-use the same interface.

    l - [ ] Load all modules   b - [ ] Build project first
    
    d - [X] Load .ghci files   o  - [X] Use -fobject-code

I.e. rather than encoding all options in various commands, pop it in a menu.

**Comment by chrisdone** [comment]
I've now implemented the support for such a UI, if you're interested! https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L1372

It's used by `intero-targets`, for example. We could present the above options using this feature.

**Comment by wuzzeb** [comment]
Ok, I implemented a small menu which uses the new intero-multiswitch.  At the moment it just has no-load and no-build, but the other options can easily be supported.  I made the options global which makes the most sense to me, do you think they should be buffer-local instead?

**Comment by chrisdone** [comment]
I'm not sure about the buffer-local vs global. I guess global works fine.

**Comment by chrisdone** [comment]
Merged! I made the changes I mentioned above. So:

1. The two options are customizations that you can configure globally for all future projects.
2. If you run `intero-repl` or `intero-repl-load` with `C-u` (prefix argument), it opens the options prompt. The options that you choose in that prompt are specific to your current project (backend buffer) only. If you restart your REPL and prompt options, it shows the previously selected options for that project.
3. Once you restart Emacs, it reverts back to your global configuration.

**Pull request closed without merging**
