### PR TITLE
Cache flycheck results when the source is unchanged

### PR DESCRIPTION
**Pull request by purcell**
This addresses #143, wherein flycheck warnings were getting lost after two flycheck passes in quick succession since the second underlying :l command simply said "ok".

The approach taken here is to note the temp buffer modification time and results for a flycheck pass, and then to simply replay them if another pass is requested with the same temp buffer mod time.

In order to make this work, we have to ensure that the mod time of the temp buffer is not updated unless its contents change, which introduces a small inefficiency: the temp file is now first quickly read before conditionally writing to it.

### CODE REVIEW

**Comment by chrisdone** [comment]
Tested it. Works great!

**Comment by purcell** [comment]
Yay, great.

**Comment by fosskers** [comment]
This has the unintended side-effect of keeping borked flycheck results when you add a new target via `intero-targets` (say, a test suite) after having already opened the file once. `intero-restart` used to make the false flycheck results go away, but now they stay until you change something.

**Comment by chrisdone** [comment]
Good point. We could perhaps invalidate our caches when we do an intero restart (which is our usual "invalidation point" for other things too).

**Comment by purcell** [comment]
Yep, maybe note the start time for the backend, and ignore cached results if they're older? Saves proactively iterating through all associated buffers after a restart and changing stuff.

**Comment by purcell** [comment]
Fixed in 065f2e7, I believe. Ping me if you find any issues.

**Comment by fosskers** [comment]
Thanks guys.

**Pull request merged**
