### PR TITLE
Fix unprefixed top-level symbol

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by chrisdone** [comment]
Closing as merge conflicts and at the issue reporting rate I'll prefer bug fixes.

**Comment by purcell** [comment]
Want me to rebase my changes against master and reopen this if they're still relevant?

**Comment by chrisdone** [comment]
@purcell Sure! By the way, I've added you as an admin. On sensible cosmetic changes like this, please feel free to apply them on master. I trust your judgment!

**Comment by purcell** [comment]
I don't think I'm actually an admin after all: I rebased these changes and got "access denied" pushing to this remote. :-(

**Comment by chrisdone** [comment]
The status of the invite says "Awaiting Purcell's response." Accept here https://github.com/commercialhaskell/intero/invitations

**Comment by purcell** [comment]
Erk, thanks. I never got an email about that the first time round, presumably because computers.

**Pull request closed without merging**
